name: Continuous Integration with Github

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Jar
        working-directory: ./naming-server
        run: mvn clean package
          
      - name: Build API Gateway Jar
        working-directory: ./api-gateway
        run: mvn clean package
          
      - name: Build Cambio Microservice Jar
        working-directory: ./cambio-service
        run: mvn clean package
          
      - name: Build Book Microservice Jar
        working-directory: ./book-service
        run: mvn clean package
          
      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build
      
